owner: NicolaiSoeborg
repo: status.xn--sb-lka.org

sites:
  - name: Forside
    url: https://xn--sb-lka.org/
  - name: IP
    url: https://ip.xn--sb-lka.org/
  - name: IPv4
    url: https://ipv4.xn--sb-lka.org/
    ipv6: false
  - name: IPv6
    url: https://ipv6.xn--sb-lka.org/
    ipv6: true
  - name: Badger
    url: https://badger.ip.xn--sb-lka.org/
  - name: Matrix
    url: https://matrix.søb.org/_matrix/federation/v1/version
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  cname: status.xn--sb-lka.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.søb.org
  introTitle: "Uptime monitor and status page."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/nicolaisoeborg/status.xn--sb-lka.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
