owner: NicolaiSoeborg
repo: status.xn--sb-lka.org

sites:
  - name: Forside
    url: https://xn--sb-lka.org/
  - name: IP
    url: https://ip.xn--sb-lka.org/
  - name: IPv4
    url: https://ipv4.xn--sb-lka.org/
    ipv6: false
  # broken: https://github.com/upptime/upptime/pull/904
  #- name: IPv6
  #  url: https://ipv6.xn--sb-lka.org/
  #  ipv6: true
  - name: Badger
    url: https://badger.xn--sb-lka.org/
  - name: Matrix
    url: https://matrix.søb.org/_matrix/federation/v1/version

status-website:
  cname: status.xn--sb-lka.org
  logoUrl: https://xn--sb-lka.org/static/img/logo.svg
  name: status.søb.org
  introTitle: "Uptime monitor and status page."
  introMessage: This status page uses **real-time** data from [this GitHub repository](https://github.com/nicolaisoeborg/status.xn--sb-lka.org).
  navbar:
    - title: Status
      href: /
    - title: Source (GitHub)
      href: https://github.com/$OWNER/$REPO
    - title: Forside
      href: https://xn--sb-lka.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
